from app.schemas import AuditMetadata, Fix, Issue


def generate_markdown_report(
    score: int,
    grade: str,
    summary: str,
    issues: list[Issue],
    fixes: list[Fix],
    metadata: AuditMetadata,
) -> str:
    """
    Generate a markdown audit report.

    Args:
        score: The readiness score (0-100)
        grade: The readiness grade
        summary: Human-readable summary
        issues: List of detected issues
        fixes: List of suggested fixes
        metadata: Audit metadata

    Returns:
        A markdown-formatted audit report string
    """
    lines: list[str] = []

    lines.append("# Agentic Readiness Audit Report")
    lines.append("")
    lines.append(f"**URL:** {metadata.url}")
    lines.append(f"**Score:** {score}/100 ({grade})")
    lines.append(f"**Checked at:** {metadata.checked_at}")
    lines.append(f"**Target stack:** {metadata.target_stack}")
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append(summary)
    lines.append("")

    if issues:
        lines.append("## Issues Found")
        lines.append("")
        lines.append(f"Found **{len(issues)}** issue(s):")
        lines.append("")
        for issue in issues:
            lines.append(
                f"- **{issue.id}** ({issue.severity} severity): {issue.description}"
            )
        lines.append("")

    if fixes:
        lines.append("## Suggested Fixes")
        lines.append("")
        lines.append(f"Generated **{len(fixes)}** fix recommendation(s):")
        lines.append("")
        for fix in fixes:
            lines.append(f"### {fix.title}")
            lines.append("")
            lines.append(f"**Priority:** {fix.priority}")
            lines.append("")
            lines.append(f"**Why it matters:** {fix.why_it_matters}")
            lines.append("")
            if fix.instructions:
                lines.append("**Instructions:**")
                lines.append("")
                for i, instruction in enumerate(fix.instructions, 1):
                    lines.append(f"{i}. {instruction}")
                lines.append("")
            if fix.code_snippet:
                lines.append("**Code snippet:**")
                lines.append("")
                lines.append("```html")
                lines.append(fix.code_snippet)
                lines.append("```")
                lines.append("")

    if not issues and not fixes:
        lines.append("## Result")
        lines.append("")
        lines.append("No issues found. This page is well-structured for agents.")
        lines.append("")

    lines.append("---")
    lines.append("")
    lines.append(
        f"*Report generated by Agentic Fixer. "
        f"Detected {metadata.issue_count} issues across "
        f"{len(metadata.detectors_run)} detectors.*"
    )
    lines.append("")

    return "\n".join(lines)
